<?php
/**
 * @file
 * social.module
 */
    /**
    * Implements hook_permission().
    */
    function social_media_permission()
    {
        return array(
    'access social media' => array(
      'title' => t('Administer Social Media'),
      'description' => t('Configure social media links.'),
    ),
  );
    }

//Configuration for Social Media module
function social_media_menu()
{
    $items['admin/config/content/social_media'] = array(
      'title'             =>  'Social Media',
      'description'       =>  'Create the list of social media icons based on the user request and show it on website',
      'page callback'     =>  'drupal_get_form',
      'page arguments' => array('social_media_form'),
      'access arguments' => array('access social media'),
      /*'page arguments'    =>   array('social_media_form'),
      'access arguments'  =>  'access content' //allow everyone access module,
      */
   );
    $items['admin/social_media'] = array(
    'title' => 'Social Media',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

    return $items;
}

    //Create the form for user can input
    function social_media_form($form, &$form_state)
    {
        $form['input_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Input Url Link'),
        "#description" => t('Only 1 link per social media site. We current support Facebook, Instagram, Twitter, LinkedIn, and Flickr.')
    );
        $form['input_url']['#attributes']['placeholder'] = t('Example: https://www.facebook.com/cwu.wildcats/');

        $form['submit_add'] = array(
        '#type' => 'submit',
        '#value' => t('Add/Save'),
        '#submit' => array('social_media_form_submit_add'),
    );
        $form['submit_edit'] = array(
        '#type' => 'submit',
        '#value' => t('Edit'),
        '#submit' => array('social_media_form_submit_edit'),
    );
        $results = db_query("SELECT * FROM {social_media}");

        $header = array(t("Social Media Name"), t("Social Media URL"));
        $rows = array();

        foreach ($results as $result) {
            $rows[$result -> id] = array(
            $result -> name,
            $result -> url,
        );
        }

        $form['table'] = array(
        '#type' => 'tableselect',
        '#header' => $header,
        '#options' => $rows,
        '#multiple' => false,
    );

        $form['submit_delete'] = array(
        '#type' => 'submit',
        '#value' => t('Remove Selection'),
        '#submit' => array('social_media_form_submit_delete'),
    );

        return $form;
    }

    //Validation form
    function social_media_form_validate($form, &$form_state)
    {
        $parse = $form_state['values']['input_url'];
        if ($parse === '') {
            return true;
        } else {
            $parse = filter_var($parse, FILTER_SANITIZE_URL);

            if (!filter_var($parse, FILTER_VALIDATE_URL)) {
                form_set_error('input_url', t('You must enter a valid url social media.'));
                return false;
            }
        }

        return true;
    }

    //Edit url entry to database
    function social_media_form_submit_edit($form, &$formstate)
    {
        $url = urlencode($formstate['values']['input_url']);
        $slash1 = "/";
        $urlName = "facebook";
        $slash2 = "/";
        $pattern = $slash1 . $urlName . $slash2;
        if (!preg_match($pattern, $url, $matches)) {
            $urlName = "instagram";
            $pattern = $slash1 . $urlName . $slash2;
            if (!preg_match($pattern, $url, $matches)) {
                $urlName = "twitter";
                $pattern = $slash1 . $urlName . $slash2;
                if (!preg_match($pattern, $url, $matches)) {
                    $urlName = "linkedin";
                    $pattern = $slash1 . $urlName . $slash2;
                    if (!preg_match($pattern, $url, $matches)) {
                        $urlName = "flickr";
                        $pattern = $slash1 . $urlName . $slash2;
                        if (!preg_match($pattern, $url, $matches)) {
                            $urlName = null;
                        }
                    }
                }
            }
        }

        $new_url = $formstate['values']['input_url'];

        if ($urlName !== null) {
            $query = db_update('social_media')
        ->fields(array(
            'url' => $new_url
        ))
        ->condition('name', $urlName, '=')
        ->execute();
            drupal_set_message(t('Your social media has been edited.'));
        } else {
            form_set_error('input_url', t('We only accept Facebook/Instagram/Twitter/Linkedin/Flickr url.'));
        }
    }

    //Delete url entry to database
    function social_media_form_submit_delete($form, &$formstate)
    {
        $result = db_select('social_media', 's')
            ->fields('s')
            ->execute();
        $num_of_results = $result->rowCount();
        $selected = $formstate['values']['table'];
        $query = db_delete('social_media')
    ->condition('id', $selected, '=')
    ->execute();
        $afterResult = db_select('social_media', 's')
                 ->fields('s')
                ->execute();
        $num_of_afterResults = $afterResult->rowCount();
        if ($num_of_afterResults < $num_of_results) {
            drupal_set_message(t('Your social media has been deleted.'));
        } else {
            drupal_set_message(t("You didn't choose any social media to delete."), 'error');
        }
    }

    //Insert entry to database
    function social_media_form_submit_add($form, &$formstate)
    {
        $url = urlencode($formstate['values']['input_url']);
        $slash1 = "/";
        $urlName = "facebook";
        $slash2 = "/";
        $pattern = $slash1 . $urlName . $slash2;
        if (!preg_match($pattern, $url, $matches)) {
            $urlName = "instagram";
            $pattern = $slash1 . $urlName . $slash2;
            if (!preg_match($pattern, $url, $matches)) {
                $urlName = "twitter";
                $pattern = $slash1 . $urlName . $slash2;
                if (!preg_match($pattern, $url, $matches)) {
                    $urlName = "linkedin";
                    $pattern = $slash1 . $urlName . $slash2;
                    if (!preg_match($pattern, $url, $matches)) {
                        $urlName = "flickr";
                        $pattern = $slash1 . $urlName . $slash2;
                        if (!preg_match($pattern, $url, $matches)) {
                            $urlName = null;
                        }
                    }
                }
            }
        }
        try {
            if ($urlName !== null) {
                $id = db_insert('social_media')
            ->fields(array(
                'name' => $urlName,
                'url' => $formstate['values']['input_url'],
            ))
            ->execute();
                drupal_set_message(t('Your social media has been added.'));
            } else {
                form_set_error('input_url', t('We only accept Facebook/Instagram/Twitter/Linkedin/Flickr url.'));
            }
        } catch (PDOException $e) {
            drupal_set_message(t("Sorry, that didn't work. Duplicate url."), 'error');
        }
    }

    //Create the HTML code (<a> tag) using the value get from client input form
    function social_media_get_value()
    {
        $result = db_query("SELECT name, url FROM {social_media}");

        $names = array();
        $urls = array();

        foreach ($result as $record) {
            $names[] = $record->name;
            $urls[] = $record->url;
        }

        $html1 = '<div
            class="sticky"
            data-sticky
            data-top-anchor="article:top"
            data-btm-anchor="article:bottom"
            data-sticky-on="large">
            <ul class="social">';
        $html2 = "";
        for ($i=0; $i<count($names); $i++) {
            $html2 .= '<li class="social__item">
                    <a
                        href="'.$urls[$i].'"
                        target="_blank">
                        <i class="fab fa-'.$names[$i].'"></i>
                    </a>
                </li>';
        }
        $html3 = '</ul></div>';
        $html = $html1 . $html2 . $html3;
        return $html;
    }

    //Create a block for module
    function social_media_block_info()
    {
        $blocks['Social Media'] = array(
      'info' => t('Social Media'),
      'cache' => DRUPAL_NO_CACHE,
    );
        return $blocks;
    }

    //Show the list of social media based on user input form
    function social_media_block_view($delta = '')
    {
        $block = array();
        switch ($delta) {
    case 'Social Media':
      $block['content'] = social_media_get_value();
      break;
  }
        return $block;
    }
